### ISSUE TITLE
PHP5.4.8 Crash

### ISSUE THREAD

**Issue by splitice** [MagicalTux/proctitle#3]
Crashes On:
PHP 5.4.8-1~dotdeb.0 (cli) (built: Oct 18 2012 21:19:48)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.2.1, Copyright (c) 2002-2012, by Derick Rethans

Works On:
PHP 5.4.7-1~dotdeb.0 (cli) (built: Sep 15 2012 09:53:20)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.2.1, Copyright (c) 2002-2012, by Derick Rethans

BackTrace / CoreDump:
#0  0x000000000066e7d4 in format_converter (odp=0x0, fmt=0x7f8474514d51 "s", ap=0x7f8479be5e40)

```
at /usr/src/php5.4/source/php5-5.4.8/main/snprintf.c:1171
```
#1  0x000000000066f88c in strx_printv (ccp=0x7fff6f1bef1c, buf=0x0, len=1864101982, format=0x7f <Address 0x7f out of bounds>, ap=0x0)

```
at /usr/src/php5.4/source/php5-5.4.8/main/snprintf.c:1213
```
#2  0x000000000066fa34 in ap_php_snprintf (buf=0x20 <Address 0x20 out of bounds>, len=0, format=0x7fff6f1bf05e " ")

```
at /usr/src/php5.4/source/php5-5.4.8/main/snprintf.c:1258
```
#3  0x00007f8474514cc8 in setproctitle (ht=<value optimized out>, return_value=<value optimized out>, return_value_ptr=<value optimized out>,

```
this_ptr=<value optimized out>, return_value_used=<value optimized out>) at /tmp/pear/temp/proctitle/proctitle.c:57
```
#4  zif_setproctitle (ht=<value optimized out>, return_value=<value optimized out>, return_value_ptr=<value optimized out>,

```
this_ptr=<value optimized out>, return_value_used=<value optimized out>) at /tmp/pear/temp/proctitle/proctitle.c:86
```
#5  0x00007f847904206b in xdebug_execute_internal () from /usr/lib/php5/20100525/xdebug.so
#6  0x0000000000745e26 in zend_do_fcall_common_helper_SPEC (execute_data=0x7f847cdff068)

```
at /usr/src/php5.4/source/php5-5.4.8/Zend/zend_vm_execute.h:644
```
#7  0x0000000000732f28 in execute (op_array=0x7f847ce2dbe0) at /usr/src/php5.4/source/php5-5.4.8/Zend/zend_vm_execute.h:410
#8  0x00007f8479042509 in xdebug_execute () from /usr/lib/php5/20100525/xdebug.so
#9  0x00000000007157b0 in ZEND_INCLUDE_OR_EVAL_SPEC_TMP_HANDLER (execute_data=0x7f847cdfb060)

```
at /usr/src/php5.4/source/php5-5.4.8/Zend/zend_vm_execute.h:7063
```
#10 0x0000000000732f28 in execute (op_array=0x7f847ce2d300) at /usr/src/php5.4/source/php5-5.4.8/Zend/zend_vm_execute.h:410
#11 0x00007f8479042509 in xdebug_execute () from /usr/lib/php5/20100525/xdebug.so
#12 0x00000000006c8940 in zend_execute_scripts (type=0, retval=0x7fff6f1bf5d0, file_count=1864103152)

```
at /usr/src/php5.4/source/php5-5.4.8/Zend/zend.c:1309
```
#13 0x000000000066a6b8 in php_execute_script (primary_file=0x0) at /usr/src/php5.4/source/php5-5.4.8/main/main.c:2482
#14 0x0000000000774f43 in do_cli (argc=32767, argv=0x7f847cdf9020) at /usr/src/php5.4/source/php5-5.4.8/sapi/cli/php_cli.c:988

**Comment by splitice** [comment]
Seems to run fine when application is run via CLI but when run from a cronjob, it crashes.

Hope you can resolve as this is an awesome extension.
